# Generated by Django 4.0.1 on 2022-07-02 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_json', models.CharField(max_length=100000)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(default='', max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('zip', models.CharField(default='', max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('card_number', models.IntegerField()),
                ('card_holder', models.CharField(default='', max_length=200)),
                ('cvv', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
