# Generated by Django 4.0.1 on 2022-07-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
