# Generated by Django 4.0.1 on 2022-07-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_order_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=10000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
