# Generated by Django 4.0.1 on 2022-07-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='update_desc',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
